# Generated by Django 3.2 on 2021-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_event', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('city', models.ManyToManyField(blank=True, default=None, to='api.City')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
