# Generated by Django 3.2 on 2021-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210418_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
